version: '3.8'

services:
  app:
    build: ./app
    container_name: todo-app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
