version: '3'

services:
  app:
    build:
      context: .
      args:
        - TAG=${TAG}  # Se pasará una etiqueta dinámica al build
    image: to-do-app:${TAG}
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
